<a href="https://colab.research.google.com/github/FrancisoL1122/Probability_Statistics/blob/main/Limongi_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [38]:
for i in range(100):# the range allows you to print the numbers you'd like
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [3]:
for i in range(5,8):
    print(i)

5
6
7


In [4]:
for i in range(3):
    print( "Test Number: " , i ) # this allows you to label them as well

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [6]:
def square(x):
    return x**2 # as we have seen in the past, you can define a function to a simple word like "square"

In [7]:
square(5)

25

In [8]:
square(square(2))

16

In [9]:
square(square(square(2)))


256

In [10]:
square(123456)

15241383936

In [11]:
square(square(5))

625

In [41]:
def add_two(x):
    return x+2 # same thing with just add 2, this allows for easy funtions

In [42]:
add_two(5)

7

In [43]:
square(add_two(5))

49

### Logical Branching

In [44]:
choice = "apple"# this is like a dialouge that requires an answer and the choice represents the option you select

In [45]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [46]:
choice = "orange" # you can have 1 choice or multiple

In [47]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [48]:
choice = "apple"

In [49]:
if choice == "apple": # you can set it to do multiple things if you make a certian choice as well as set up different responses depending on the choice

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [50]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): 


In [51]:
choice

''

In [52]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You did not choose apples or oranges.


#### Coins

In [55]:
import numpy as np


In [57]:
np.random.random() # as we have seen previously, random numbers can be generated in order to make a true 50/50 coin flip

0.15164869324792185

In [58]:
np.random.random() > 0.5

True

In [59]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [60]:
flip_coin()

Heads


### Graphics Output

In [61]:
from IPython.core.display import display, HTML

In [62]:
display(HTML('<h1>Hello, world!</h1>')) # displaying text using HTML

In [63]:
def coin():
  return np.random.randint(2) # defining coin using a radint

In [64]:
coin()

0

In [65]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [66]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' #defining heads and tails to have images attached to them

In [67]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [68]:
show_img(heads)

In [69]:
show_img(tails)

In [70]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [71]:
flip_coin()

In [72]:
for i in range(5):
    flip_coin() #fliping 5 coins shows the fairness of the 50/50

In [84]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [74]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x # This sections shows how you can create a deck of cards

In [75]:
a = np.arange(52) # this is how many cards are in a deck

In [76]:
shuffle(a) # this shuffles the numbers

array([50, 10, 13, 27, 39, 17, 18, 11, 48, 33, 37,  0, 25, 24, 38, 12, 34,
       20, 36, 14, 15,  7,  1, 21,  5, 32, 35, 22, 44, 46,  9, 30, 29,  8,
       19, 41, 45, 28, 16, 26,  6, 47, 49, 43, 42, 51, 23, 31,  2,  3, 40,
        4])

In [77]:
np.random.permutation(52) # and this will do about the same thing

array([38,  0,  7, 28, 31, 48, 14, 37, 35, 10,  8, 42,  1, 26, 27, 51, 21,
        2, 16, 18, 13, 32, 49, 43, 30, 45, 39, 34, 47, 20, 23, 33, 29, 22,
        3, 25, 50,  4, 19,  5, 17, 44, 12, 15, 41, 40, 24,  6, 46, 36,  9,
       11])

### Speed Test

In [78]:
%%timeit
shuffle(a)

128 µs ± 1.88 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [79]:
%%timeit
np.random.permutation(52)

4.18 µs ± 1.65 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [80]:
import numpy as np

In [85]:
np.random.permutation(52)

array([19, 31, 49,  2,  3, 23, 11, 34, 45, 32, 17, 39, 26, 33, 16, 15, 50,
        4, 37,  9,  0, 48, 30, 18,  8, 13, 42, 22, 41, 47, 21, 43, 51, 40,
       35, 46, 12, 28, 24, 44, 38,  7, 27, 29,  5, 36, 14,  1,  6, 25, 20,
       10])

In [86]:
cards = np.random.permutation(52)

In [87]:
cards

array([13, 27,  9, 31,  8, 34, 22, 45, 46, 44, 12, 16,  1,  7, 23,  5, 48,
       43, 19, 39, 21, 49, 10,  6, 25, 20, 50, 18, 24,  4, 37, 33,  0, 35,
        3, 30, 40, 38, 32, 47, 11, 51, 14,  2, 26, 15, 41, 42, 17, 28, 36,
       29])

In [88]:
cards[0] # this will allow you to draw a specific card in the deck

13

In [89]:
cards[1]

27

In [90]:
cards[2]

9

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [92]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [93]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [94]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [95]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] # this is defining the cards to have suits and values

In [96]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit] #this sets up the suits and values

In [97]:
card_name(0)

'Ace of Clubs'

In [98]:
card_name(51) # this is the final result

'King of Diamonds'

In [100]:
cards = np.random.permutation(52)

In [103]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1]) #defining this allows us to see what card is where in the deck

In [104]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Two of Clubs', 'Six of Spades', 'Five of Clubs')

In [105]:
for i in range(5):
    print(card_name(cards[i])) #randomly prints 5 cards

Two of Clubs
Six of Spades
Three of Clubs
Seven of Clubs
Three of Spades


In [106]:
for i in range(15):
    print(card_name(cards[i])) #now 15

Two of Clubs
Six of Spades
Three of Clubs
Seven of Clubs
Three of Spades
Four of Clubs
Six of Clubs
Jack of Hearts
Jack of Clubs
Ten of Spades
Queen of Spades
Ace of Hearts
Seven of Hearts
Two of Diamonds
Nine of Spades


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [107]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [108]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [110]:
i = np.random.randint(4)
j = np.random.randint(13)

In [111]:
i,j

(1, 2)

In [112]:
suit[i]

'p'

In [113]:
card[j]

'3'

In [114]:
from IPython.core.display import display, HTML

In [115]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [116]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [117]:
show_img(img) #shows you the card you drew

In [ ]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [ ]:
card_image(3)

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
show_img(img)

In [25]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)

NameError: ignored